import { Injectable } from '@nestjs/common';
import { EntityManager } from 'typeorm';
import { RevisionsRepository } from './repositories/revisions.repository';
import { RevisionEntityType, RevisionOrigin, RevisionStatus } from './revision.enums';
import { toWikiRevision } from './revisions.mapper';

export interface RecordPlaceRevisionInput {
  placeId: string;
  // Snapshot nội dung được serialize sang jsonb → chấp nhận mọi object JSON (kể cả DTO
  // có kiểu cụ thể như PlaceCard). Record<string, unknown> quá hẹp: từ chối interface.
  snapshot: object;
  diff?: Record<string, unknown> | null;
  origin: RevisionOrigin;
  changeNote?: string | null;
  editorId?: string | null;
  status: RevisionStatus;
}

// ADR-020 §5: entityId is the place_translations/route/seo row's OWN id (pre-generated by the
// caller), never placeId — see the method doc on recordPlaceTranslationRevision() for why.
export interface RecordPlaceTranslationRevisionInput {
  entityId: string;
  snapshot: object;
  diff?: Record<string, unknown> | null;
  origin: RevisionOrigin;
  changeNote?: string | null;
  editorId?: string | null;
  status: RevisionStatus;
}

// Dịch vụ phiên bản (WikiRevision). Ghi vết mỗi thay đổi nội dung (WF-14) và
// phục vụ lịch sử công khai. Vòng đời duyệt đầy đủ (pending→approved→materialize
// snapshot) thuộc Sprint 4 (Contributions/Moderation).
@Injectable()
export class RevisionsService {
  constructor(private readonly revisionsRepo: RevisionsRepository) {}

  recordPlaceRevision(input: RecordPlaceRevisionInput): Promise<{ id: string; revisionNumber: number }> {
    return this.revisionsRepo.record({
      entityType: RevisionEntityType.PLACE,
      entityId: input.placeId,
      snapshot: input.snapshot,
      diff: input.diff ?? null,
      origin: input.origin,
      changeNote: input.changeNote ?? null,
      editorId: input.editorId ?? null,
      status: input.status,
    });
  }

  async listByPlace(placeId: string) {
    const rows = await this.revisionsRepo.listByEntity(RevisionEntityType.PLACE, placeId);
    return rows.map(toWikiRevision);
  }

  // ADR-020 §5: one wiki_revisions row per changed place_translations/route/seo RECORD, never one
  // shared row per publish-bundle. Those tables are insert-only (a new locale-slot value is a new
  // row, the old one flips is_current=false) — so unlike PLACE, entityId cannot be a stable id that
  // outlives the write; it IS the record's own id. The caller must pre-generate that id (e.g.
  // `randomUUID()`) BEFORE calling this, so the same id can be used both as this revision's
  // entityId and as the row's own primary key when it inserts immediately after — otherwise the two
  // rows could never reference each other (place_translations.revision_id needs a real revision id,
  // and this revision needs the row's real id, in the same transaction).
  recordPlaceTranslationRevision(
    input: RecordPlaceTranslationRevisionInput,
    manager?: EntityManager,
  ): Promise<{ id: string; revisionNumber: number }> {
    return this.revisionsRepo.record(
      {
        entityType: RevisionEntityType.PLACE_TRANSLATION,
        entityId: input.entityId,
        snapshot: input.snapshot,
        diff: input.diff ?? null,
        origin: input.origin,
        changeNote: input.changeNote ?? null,
        editorId: input.editorId ?? null,
        status: input.status,
      },
      manager,
    );
  }
}
