#!/bin/bash
# Validates a Vinpearl Safari evidence intake batch: local files only, no network, no database.
#
# What it does:
#   - reads evidence-intake-manifest.csv and files/ in THIS directory only
#   - rejects empty/zero-byte files, symlinks, and malformed manifest rows
#   - rejects a file_name that contains '/' (no traversing out of files/, no subdirectories)
#   - rejects any manifest field that starts with '=' '+' '-' '@' or a tab (CSV/DDE
#     formula-injection prefixes a spreadsheet could execute when the manifest is opened)
#   - determines each file's MIME type (informational, via `file`)
#   - computes the REAL SHA-256 of each file's bytes and compares it to the manifest's sha256
#     column (never trusts a hand-typed hash)
#   - flags duplicate evidence_id values and duplicate content hashes across rows
#   - flags files present in files/ but not referenced by any manifest row
#   - writes every real computed hash to checksums.sha256 (sha256sum format)
#   - prints every finding, then an overall PASS / HOLD / FAIL verdict
#
# What it will NEVER do: fetch a URL, open a network socket, or connect to any database. If you
# are reading this expecting it to import evidence somewhere — it does not, and importing evidence
# is a separate, explicitly-approved task, not something this script escalates into.
#
# Manifest field constraint: fields must not contain a literal comma (this parser is comma-naive,
# not quote-aware) — use ";" or " - " instead. A row whose comma count is wrong is flagged FAIL.
#
# Usage: ./verify-evidence-files.sh  (run from this directory)
set -uo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

MANIFEST="evidence-intake-manifest.csv"
FILES_DIR="files"
CHECKSUMS="checksums.sha256"
REQUIRED_COLS="evidence_id,environment,place_id,file_name,source_url,captured_at,page_title,claim_supported,sha256,reuse_note,reviewed_by"
NUM_COLS=11

PROD_PLACE_ID="7ab06900-8d98-4222-8cfd-794526e65667"
STAGING_PLACE_PREFIX="8381328d-"

# A field starting with '=', '+', '-', '@', or a tab is a classic CSV/DDE formula-injection
# trigger in Excel/Google Sheets (e.g. `=cmd|'/c calc'!A1`, `=HYPERLINK(...)`). This manifest is
# handed to a human reviewer who will very likely open it in a spreadsheet, so any free-text field
# is rejected outright rather than passed through as "just text".
is_formula_injection() {
  case "$1" in
    '='*|'+'*|'-'*|'@'*|"$(printf '\t')"*) return 0 ;;
    *) return 1 ;;
  esac
}

[ -f "$MANIFEST" ] || { echo "[verify] FAIL: $MANIFEST not found."; exit 1; }
mkdir -p "$FILES_DIR"

echo "[verify] Vinpearl Safari evidence intake — local file check only, no network, no database."
echo "[verify] Directory: $SCRIPT_DIR"
echo

header=$(head -n1 "$MANIFEST" | tr -d '\r')
if [ "$header" != "$REQUIRED_COLS" ]; then
  echo "[verify] FAIL: manifest header does not match expected columns."
  echo "[verify]   expected: $REQUIRED_COLS"
  echo "[verify]   actual:   $header"
  exit 1
fi

# --- Recompute real checksums for every file actually present in files/ -----------------------
{
  echo "# Auto-generated by verify-evidence-files.sh — do not hand-edit."
  echo "# Real SHA-256 of every file in files/, computed at validator run time."
} > "$CHECKSUMS"
present_files=0
fail_count=0
hold_count=0
if [ -d "$FILES_DIR" ]; then
  while IFS= read -r -d '' f; do
    base=$(basename "$f")
    # Dotfiles (.gitkeep, .gitignore, .DS_Store, ...) are directory-tracking/OS noise, never
    # evidence candidates -- skip them entirely rather than flagging a fresh checkout as FAIL.
    case "$base" in
      .*) continue ;;
    esac
    present_files=$((present_files + 1))
    if [ -L "$f" ]; then
      echo "[verify] FAIL: $base is a symlink, not a real file — evidence must be actual captured bytes, not a link to something else."
      fail_count=$((fail_count + 1))
      continue
    fi
    if [ ! -s "$f" ]; then
      echo "[verify] FAIL: $base is empty (zero bytes) — cannot be evidence."
      fail_count=$((fail_count + 1))
      continue
    fi
    h=$(sha256sum "$f" | awk '{print $1}')
    echo "$h  $base" >> "$CHECKSUMS"
  done < <(find "$FILES_DIR" -maxdepth 1 -type f -print0 | sort -z)
fi
echo "[verify] $present_files file(s) found in $FILES_DIR/, checksums written to $CHECKSUMS."
echo

# --- Walk the manifest, one data row at a time (no trailing pipe -> stays in this shell) ------
declare -a seen_ids=()
declare -a seen_hashes=()
declare -a referenced_files=()
row_count=0

while IFS= read -r raw_line || [ -n "$raw_line" ]; do
  raw_line=${raw_line%$'\r'}
  [ -z "$raw_line" ] && continue
  row_count=$((row_count + 1))

  comma_count=$(grep -o ',' <<<"$raw_line" | wc -l)
  if [ "$comma_count" -ne $((NUM_COLS - 1)) ]; then
    echo "[verify] FAIL (row $row_count): expected $NUM_COLS comma-separated fields, found $((comma_count + 1)) — a field may contain a literal comma, which this parser cannot handle."
    fail_count=$((fail_count + 1))
    continue
  fi

  IFS=',' read -r evidence_id environment place_id file_name source_url captured_at page_title claim_supported sha256 reuse_note reviewed_by <<<"$raw_line"

  [ -z "$evidence_id" ] && { echo "[verify] FAIL (row $row_count): evidence_id is empty."; fail_count=$((fail_count + 1)); continue; }

  row_had_fail=0

  for existing in "${seen_ids[@]:-}"; do
    if [ "$existing" = "$evidence_id" ]; then
      echo "[verify] FAIL ($evidence_id): duplicate evidence_id in manifest."
      row_had_fail=1
    fi
  done
  seen_ids+=("$evidence_id")

  case "$environment" in
    production|staging) : ;;
    *)
      echo "[verify] FAIL ($evidence_id): environment must be 'production' or 'staging', got '$environment'."
      row_had_fail=1
      ;;
  esac

  if [ "$environment" = "production" ] && [ "$place_id" != "$PROD_PLACE_ID" ]; then
    echo "[verify] FAIL ($evidence_id): environment=production but place_id='$place_id' != $PROD_PLACE_ID."
    row_had_fail=1
  fi
  if [ "$environment" = "staging" ]; then
    case "$place_id" in
      "$STAGING_PLACE_PREFIX"*) : ;;
      *)
        echo "[verify] FAIL ($evidence_id): environment=staging but place_id='$place_id' does not start with $STAGING_PLACE_PREFIX."
        row_had_fail=1
        ;;
    esac
  fi

  for pair in "file_name=$file_name" "source_url=$source_url" "captured_at=$captured_at" \
    "page_title=$page_title" "claim_supported=$claim_supported" "sha256=$sha256" "reviewed_by=$reviewed_by"; do
    fname=${pair%%=*}
    fval=${pair#*=}
    if [ -z "$fval" ]; then
      echo "[verify] FAIL ($evidence_id): required field '$fname' is empty."
      row_had_fail=1
    fi
  done

  # Free-text fields only -- environment/place_id/sha256 are already validated against strict
  # patterns above/below, so a formula-injection prefix there is caught as an invalid value anyway.
  for pair in "evidence_id=$evidence_id" "file_name=$file_name" "source_url=$source_url" \
    "captured_at=$captured_at" "page_title=$page_title" "claim_supported=$claim_supported" \
    "reuse_note=$reuse_note" "reviewed_by=$reviewed_by"; do
    fname=${pair%%=*}
    fval=${pair#*=}
    if [ -n "$fval" ] && is_formula_injection "$fval"; then
      echo "[verify] FAIL ($evidence_id): field '$fname' starts with a character ('=' '+' '-' '@' or tab) that Excel/Sheets can interpret as a formula — rejecting rather than passing it through to a reviewer's spreadsheet."
      row_had_fail=1
    fi
  done

  file_name_invalid=0
  if [ -n "$file_name" ]; then
    referenced_files+=("$file_name")
    case "$file_name" in
      */*)
        echo "[verify] FAIL ($evidence_id): file_name '$file_name' contains '/' — must be a plain filename directly inside $FILES_DIR/, not a path. Refusing to resolve outside the evidence directory."
        row_had_fail=1
        file_name_invalid=1
        ;;
    esac
  fi
  if [ -n "$file_name" ] && [ "$file_name_invalid" != 1 ]; then
    target="$FILES_DIR/$file_name"
    if [ -L "$target" ]; then
      echo "[verify] FAIL ($evidence_id): '$file_name' is a symlink, not a real file — evidence must be actual captured bytes, not a link to something else."
      row_had_fail=1
    elif [ ! -f "$target" ]; then
      echo "[verify] FAIL ($evidence_id): file_name '$file_name' not found in $FILES_DIR/."
      row_had_fail=1
    elif [ ! -s "$target" ]; then
      echo "[verify] FAIL ($evidence_id): '$file_name' is empty (zero bytes)."
      row_had_fail=1
    else
      actual_sha=$(sha256sum "$target" | awk '{print $1}')
      if [ -n "$sha256" ] && [ "$sha256" != "$actual_sha" ]; then
        echo "[verify] FAIL ($evidence_id): manifest sha256 does not match the file's real bytes."
        echo "[verify]   manifest: $sha256"
        echo "[verify]   actual:   $actual_sha"
        row_had_fail=1
      fi
      for existing_hash in "${seen_hashes[@]:-}"; do
        if [ "$existing_hash" = "$actual_sha" ]; then
          echo "[verify] HOLD ($evidence_id): this file's content hash matches an earlier row — possible duplicate evidence."
          hold_count=$((hold_count + 1))
        fi
      done
      seen_hashes+=("$actual_sha")

      mime=$(file --brief --mime-type "$target" 2>/dev/null || echo "unknown")
      case "$mime" in
        image/*|application/pdf) : ;;
        *)
          echo "[verify] HOLD ($evidence_id): unexpected file type '$mime' for '$file_name' — expected an image or a PDF."
          hold_count=$((hold_count + 1))
          ;;
      esac
    fi
  fi

  if [ "$reuse_note" = "unsure" ]; then
    echo "[verify] HOLD ($evidence_id): reuse_note is 'unsure' — needs a human call before this evidence is forwarded."
    hold_count=$((hold_count + 1))
  fi

  [ "$row_had_fail" = 1 ] && fail_count=$((fail_count + 1))
done < <(tail -n +2 "$MANIFEST")

echo
echo "[verify] --- Unreferenced files check ---"
if [ -d "$FILES_DIR" ]; then
  while IFS= read -r -d '' f; do
    base=$(basename "$f")
    case "$base" in
      .*) continue ;;
    esac
    found=0
    for ref in "${referenced_files[@]:-}"; do
      [ "$ref" = "$base" ] && { found=1; break; }
    done
    if [ "$found" = 0 ]; then
      echo "[verify] HOLD: '$base' is in $FILES_DIR/ but not referenced by any manifest row."
      hold_count=$((hold_count + 1))
    fi
  done < <(find "$FILES_DIR" -maxdepth 1 -type f -print0 | sort -z)
fi

echo
echo "[verify] === Summary ==="
echo "[verify] Manifest rows: $row_count   Files checked: $present_files"
echo "[verify] FAIL findings: $fail_count   HOLD findings: $hold_count"
if [ "$fail_count" -gt 0 ]; then
  echo "[verify] RESULT: FAIL — do not forward this batch for evidence review."
  exit 1
elif [ "$hold_count" -gt 0 ]; then
  echo "[verify] RESULT: HOLD — needs a human decision on the item(s) above before forwarding."
  exit 0
else
  echo "[verify] RESULT: PASS — files are present, non-empty, hash-matched, and fully referenced."
  exit 0
fi
